### ISSUE TITLE
I cannot find "ChannelApiFrameworkv2_SampleApp.zip"

### ISSUE THREAD

**Issue by ShunyaWatanabe** [microsoft/Dynamics365-Apps-Samples#19]
I am trying to follow the instruction [here](https://github.com/microsoft/Dynamics365-Apps-Samples/tree/master/customer-service/channel-integration-framework/TwilioSampleInteg_version2) but I cannot find the zip file.

**Comment by susikka** [comment]
@ShunyaWatanabe The `sample_data_cifv2.zip` file is available here in the [CIF V2 sample](https://github.com/microsoft/Dynamics365-Apps-Samples/tree/master/customer-service/channel-integration-framework/TwilioSampleInteg_version2) folder. Closing this issue now.

**Comment by ShunyaWatanabe** [comment]
What I meant is that the readme file is unclear and if it is talking about the folder it self, not a zip file, it should say so
