### ISSUE TITLE
Unable to See response from Smart Assist Bot

### ISSUE THREAD

**Issue by Aavi2105** [microsoft/Dynamics365-Apps-Samples#28]
Hi - I need to enable smart assist inside omni channel app and I have followed the above steps , but unable to get any response in test web chat. Even i tried running locally using bit emulater , but getting no response / error. PFB screen shot. Please assist.

![image](https://user-images.githubusercontent.com/68352642/87594148-21193580-c6b2-11ea-822f-e686e1e7810e.png)

Thanks
Aavi

**Comment by susikka** [comment]
@Aavi2105 this looks like a support issue to me. Unfortunately, we cannot handle support requests for the product here. Suggest that you try contacting [Dynamics 365 support](https://dynamics.microsoft.com/support/).

Closing this issue.
